"""
Abbreviated reporting guideline checklists.

Only the items most commonly flagged by peer reviewers are included - these
catch the majority of desk-rejection risks without overwhelming the LLM.
Full checklists are maintained by the EQUATOR Network (equator-network.org).
"""

from __future__ import annotations


REPORTING_GUIDELINES: dict[str, dict] = {
    "CONSORT": {
        "full_name": "Consolidated Standards of Reporting Trials",
        "study_types": ["randomized controlled trial", "rct", "clinical trial"],
        "items": [
            ("1a", "Title identifies the study as a randomised trial"),
            ("2a", "Background: scientific rationale for the trial"),
            ("3a", "Participants: eligibility criteria"),
            ("4a", "Interventions: precise details of interventions for each group"),
            ("5", "Outcomes: primary and secondary outcomes defined"),
            ("6a", "Sample size: how sample size was determined"),
            ("7a", "Randomization: sequence generation method"),
            ("8a", "Allocation concealment: mechanism used"),
            ("9", "Blinding: who was blinded and how"),
            ("10", "Statistical methods: methods used to compare groups"),
            ("11a", "Participant flow: number randomized, received treatment, analyzed"),
            ("12a", "Recruitment: dates of recruitment and follow-up"),
            ("13a", "Baseline data: baseline demographic and clinical characteristics"),
            ("14a", "Numbers analysed: number in each group for each outcome"),
            ("15", "Outcomes: estimated effect size and precision (CI)"),
            ("16", "Ancillary analyses: subgroup and adjusted analyses"),
            ("17a", "Harms: all important adverse events by group"),
            ("18", "Limitations: trial limitations, addressing bias and imprecision"),
            ("19", "Generalisability: of the trial findings"),
            ("20", "Interpretation: consistent with results, balancing benefits and harms"),
            ("23", "Registration: registration number and registry name"),
            ("24", "Protocol: where the full protocol can be accessed"),
            ("25", "Funding: sources of funding and role of funders"),
        ],
    },
    "STROBE": {
        "full_name": "Strengthening the Reporting of Observational Studies in Epidemiology",
        "study_types": [
            "observational", "cohort", "case-control", "cross-sectional",
            "retrospective", "prospective",
        ],
        "items": [
            ("1", "Title/abstract: indicates study design"),
            ("2", "Background: scientific background and rationale"),
            ("3", "Objectives: specific objectives and hypotheses"),
            ("4", "Study design: key elements of study design"),
            ("5", "Setting: setting, locations, and relevant dates"),
            ("6", "Participants: eligibility criteria, sources, and methods of selection"),
            ("7", "Variables: outcomes, exposures, predictors, confounders defined"),
            ("8", "Data sources: data sources and measurement methods"),
            ("9", "Bias: efforts to address potential sources of bias"),
            ("10", "Study size: how study size was arrived at"),
            ("11", "Quantitative variables: how quantitative variables were handled"),
            ("12", "Statistical methods: all statistical methods described"),
            ("13", "Participants: numbers at each stage and reasons for non-participation"),
            ("14", "Descriptive data: characteristics of participants"),
            ("15", "Outcome data: number of outcome events or summary measures"),
            ("16", "Main results: unadjusted and adjusted estimates with CI and p-values"),
            ("17", "Other analyses: other analyses done (subgroup, interaction, sensitivity)"),
            ("18", "Key results: summarise key results with reference to objectives"),
            ("19", "Limitations: discuss limitations including bias and generalisability"),
            ("20", "Interpretation: cautious interpretation considering objectives and limitations"),
            ("21", "Generalisability: discuss generalisability of results"),
            ("22", "Funding: sources of funding and role of funders"),
        ],
    },
    "TRIPOD": {
        "full_name": "Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis",
        "study_types": [
            "prediction model", "diagnostic model", "prognostic model",
            "machine learning", "deep learning", "classifier", "risk score",
        ],
        "items": [
            ("1", "Title: identifies as development/validation of prediction model"),
            ("2", "Abstract: structured summary of objectives, methods, results"),
            ("3a", "Background: context and rationale for the prediction model"),
            ("4a", "Objectives: study objectives including whether development/validation"),
            ("5a", "Source of data: describe the study design and setting"),
            ("6a", "Participants: eligibility criteria for participants"),
            ("7a", "Outcomes: clearly define the outcome"),
            ("8", "Predictors: all predictors defined including timing of measurement"),
            ("9", "Sample size: how study size was arrived at"),
            ("10a", "Missing data: how missing data were handled"),
            ("10b", "Model development: how predictors were handled in modelling"),
            ("10d", "Model specification: full model specification including coefficients"),
            ("11", "Risk groups: if risk groups created, how and why"),
            ("12", "Development vs validation: how this was done"),
            ("13a", "Flow of participants through the study"),
            ("14a", "Participant characteristics and outcome counts"),
            ("15a", "Model development: present full model with coefficients"),
            ("16", "Model performance: discrimination and calibration measures"),
            ("17", "Model updating: if model was updated, describe"),
            ("18", "Discussion: limitations of the study"),
            ("19a", "Interpretation: consider clinical use and limitations"),
            ("20", "Supplementary: provide model in usable format"),
        ],
    },
    "PRISMA": {
        "full_name": "Preferred Reporting Items for Systematic Reviews and Meta-Analyses",
        "study_types": ["systematic review", "meta-analysis", "scoping review"],
        "items": [
            ("1", "Title: identifies report as systematic review/meta-analysis"),
            ("2", "Abstract: structured summary"),
            ("3", "Rationale: what is known and what the review adds"),
            ("4", "Objectives: explicit statement of questions addressed"),
            ("5", "Protocol: whether a review protocol exists"),
            ("6", "Eligibility criteria: PICOS inclusion/exclusion criteria"),
            ("7", "Information sources: databases searched with dates"),
            ("8", "Search strategy: full electronic search for at least one database"),
            ("9", "Study selection: process of selecting studies"),
            ("10", "Data collection: process of extracting data"),
            ("11", "Risk of bias: methods for assessing bias in studies"),
            ("12", "Summary measures: principal summary measures"),
            ("13", "Synthesis of results: methods for combining results"),
            ("17", "Study selection: give numbers at each stage with reasons"),
            ("18", "Study characteristics: data for each study"),
            ("20", "Results of individual studies: data for each study and forest plots"),
            ("21", "Synthesis of results: present results of meta-analysis with CI"),
            ("22", "Risk of bias across studies"),
            ("24", "Summary of evidence: summarise main findings including quality"),
            ("25", "Limitations: discuss limitations at study and outcome level"),
            ("27", "Funding: sources of funding for the review"),
        ],
    },
    "STARD": {
        "full_name": "Standards for Reporting of Diagnostic Accuracy Studies",
        "study_types": [
            "diagnostic accuracy", "sensitivity specificity",
            "diagnostic test", "screening test", "biomarker validation",
        ],
        "items": [
            ("1", "Title: identifies as diagnostic accuracy study"),
            ("2", "Abstract: structured summary of design, methods, results"),
            ("3", "Scientific and clinical background and rationale"),
            ("4", "Study objectives and hypotheses"),
            ("5", "Whether prospective or retrospective data collection"),
            ("6", "Eligibility criteria"),
            ("7", "On what basis potentially eligible participants were identified"),
            ("8a", "Index test: described in detail for replication"),
            ("9a", "Reference standard: described in detail for replication"),
            ("10a", "Whether participants formed a consecutive, random, or convenience series"),
            ("12a", "Pre-specified or exploratory test positivity cut-offs"),
            ("13a", "Methods for estimating diagnostic accuracy and uncertainty"),
            ("14", "How missing data on index test and reference standard were handled"),
            ("18", "Severity of disease in those with the target condition"),
            ("19", "Cross tabulation of test results by reference standard"),
            ("21a", "Estimates of diagnostic accuracy with confidence intervals"),
            ("24", "Estimates of diagnostic accuracy with measures of statistical uncertainty"),
        ],
    },
}
